---
# tasks file for zsh_role
- name: Install ZSH
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Change user shell to zsh 
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Copy zshrc
  ansible.builtin.copy:
    src: zshrc
    dest: ~/.zshrc
    mode: 0644