---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python in Ubuntu
      ansible.builtin.raw: >
        apt update && \
        apt install -y --no-install-recommends python3 sudo
      when: "'ubuntu' is in lookup('ansible.builtin.env', 'MOLECULE_DISTRO')"