---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance-ubuntu
    image: ubuntu:jammy
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
